# fly.toml app configuration file generated for server-broken-hill-5642 on 2025-10-31T18:11:12+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-broken-hill-5642'
primary_region = 'bom'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 3121
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
